USE [Teste]
GO

IF OBJECT_ID('P_NOTA_FISCAL_ITEM_IMPOSTOS_CFOP') IS NOT NULL
BEGIN
	DROP PROCEDURE dbo.P_NOTA_FISCAL_ITEM_IMPOSTOS_CFOP
	IF OBJECT_ID('dbo.P_NOTA_FISCAL_ITEM_IMPOSTOS_CFOP') IS NOT NULL
		PRINT('<<<FALHA APAGANDO A PROCEDURE dbo.P_NOTA_FISCAL_ITEM_IMPOSTOS_CFOP >>>')
	ELSE
		PRINT('<<< PROCEDURE dbo.P_NOTA_FISCAL_ITEM_IMPOSTOS_CFOP APAGADA >>>')
END
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
CREATE PROCEDURE P_NOTA_FISCAL_ITEM_IMPOSTOS_CFOP

AS
BEGIN
	SELECT 
	Cfop as 'CFOP',
	SUM(BaseIcms) as 'Valor Total Base de ICMS',
	SUM(ValorIcms) as 'Valor Total do ICMS',
	SUM(BaseIpi) as 'Valor Total Base de IPI',
	SUM(ValorIpi) as 'Valor Total do IPI'
	
	FROM NotaFiscalItem

	GROUP BY Cfop 
END
GO
GRANT EXECUTE ON dbo.P_NOTA_FISCAL_ITEM_IMPOSTOS_CFOP TO [public]
GO
IF OBJECT_ID('dbo.P_NOTA_FISCAL_ITEM_IMPOSTOS_CFOP') IS NOT NULL
	PRINT '<<< PROCEDURE dbo.P_NOTA_FISCAL_ITEM_IMPOSTOS_CFOP CRIADA >>>'
ELSE
	PRINT '<<< FALHA NA CRIACAO DA PROCEDURE dbo.P_NOTA_FISCAL_ITEM_IMPOSTOS_CFOP >>>'
